### ISSUE TITLE
Documentation code gives error for "CrossJoin"

### ISSUE THREAD

**Issue by Farreeda** [MechanicalRabbit/FunSQL.jl#42]
When I run this line, copied from the documentation, error message appears => `CrossJoin is undefined`
`using FunSQL:
    FunSQL, Agg, Append, As, Asc, Bind, CrossJoin, Define, Desc, Fun, From,
    Get, Group, Highlight, Iterate, Join, LeftJoin, Limit, Lit, Order,
    Partition, Select, Sort, Var, Where, With, WithExternal, render`

**Comment by xitology** [comment]
`CrossJoin` was added in v0.11.0. Please make sure you are using the latest version of FunSQL.

**Comment by Farreeda** [comment]
oh, noticed :D
