### ISSUE TITLE
Adding grouping sets, rollup and cube

### ISSUE THREAD

**Issue by clarkevans** [MechanicalRabbit/FunSQL.jl#50]
It would be lovely to directly support grouping sets, rollup and cube.  This is related also to sorting nulls last when the sort is otherwise descending order and nulls would come first. Supporting automatic naming for aggregates is also important.

See hacked implementation at https://github.com/TuftsCTSI/TRDW.jl/commit/89cb917bbc920f390cb0b0477ae0879f2d4054d1#diff-754e6441f2054c00a80b0953b1876f78a4f3e85993eebd6fa0e3b883611a58caR182-R212

**Comment by xitology** [comment]
Added in 5cfaebd1352594310d19f2b7fa2524e02b22f5fd
