### ISSUE TITLE
smarter Or

### ISSUE THREAD

**Issue by clarkevans** [MechanicalRabbit/FunSQL.jl#57]
I find that I have to write the following for Or to be useful.

```
function build_or(items...)
    if length(items) == 0
        return @funsql(false)                       
    end
    if length(items) == 1
        return items[1]    
    end
    return @funsql(or($items...))
end
```

**Comment by xitology** [comment]
That's how it works already, see https://github.com/MechanicalRabbit/FunSQL.jl/blob/master/src/translate.jl#L257-L293. You can write `@funsql or(args = items)`.
